### ISSUE TITLE
Set up Sphinx and readthedocs documentation generation for this repository

### ISSUE THREAD

**Issue by mithro** [antmicro/litex-rowhammer-tester#2]
You colleague, @rw1nkler can provide a bunch of advice here.

**Comment by mithro** [comment]
FYI -- @kgugala can you give @rw1nkler some time to help get this set up for this team?

**Comment by rw1nkler** [comment]
@mithro I already talked with the team about this project and gave them some advice. 
Hopefully, the documentation will show up soon. 

FYI @jedrzejboczar

**Comment by kgugala** [comment]
Initial (autogenerated) documentation is already there - https://antmicro.github.io/litex-rowhammer-tester/. Need to update it with some nicer theme and additional information. Currently it just lists registers in the system.

**Comment by tjurtsch** [comment]
Sphinx documentation on RTD is here https://litex-rowhammer-tester.readthedocs.io/en/latest/index.html
