### ISSUE TITLE
Getting a warning in 'make upload'

### ISSUE THREAD

**Issue by sqazi** [antmicro/litex-rowhammer-tester#20]
Is this normal (especially the line at the bottom)?

make upload
make[1]: Entering directory '/home/sqazi/fpga/litex-rowhammer-tester'
python rowhammer_tester/targets/zcu104.py --load --ip-address 192.168.1.10 --mac-address 0x10e2d5000001 --udp-port 1234
INFO:SoC:        __   _ __      _  __  
INFO:SoC:       / /  (_) /____ | |/_/  
INFO:SoC:      / /__/ / __/ -_)>  <    
INFO:SoC:     /____/_/\__/\__/_/|_|  
INFO:SoC:  Build your hardware, easily!
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Creating SoC... (2020-12-04 19:09:09)
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:FPGA device : xczu7ev-ffvc1156-2-i.
INFO:SoC:System clock: 125.00MHz.
INFO:SoCBusHandler:Creating Bus Handler...
INFO:SoCBusHandler:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoCBusHandler:Adding reserved Bus Regions...
INFO:SoCBusHandler:Bus Handler created.
INFO:SoCCSRHandler:Creating CSR Handler...
INFO:SoCCSRHandler:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
INFO:SoCCSRHandler:Adding reserved CSRs...
INFO:SoCCSRHandler:CSR Handler created.
INFO:SoCIRQHandler:Creating IRQ Handler...
INFO:SoCIRQHandler:IRQ Handler (up to 32 Locations).
INFO:SoCIRQHandler:Adding reserved IRQs...
INFO:SoCIRQHandler:IRQ Handler created.
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Initial SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoC:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
INFO:SoC:IRQ Handler (up to 32 Locations).
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCCSRHandler:ctrl CSR allocated at Location 0.
INFO:SoCBusHandler:io0 Region added at Origin: 0x00000000, Size: 0x100000000, Mode: RW, Cached: False Linker: False.
INFO:SoCCSRHandler:identifier_mem CSR allocated at Location 1.
INFO:SoCCSRHandler:uart_phy CSR allocated at Location 2.
INFO:SoCCSRHandler:uart CSR allocated at Location 3.
INFO:SoCCSRHandler:timer0 CSR allocated at Location 4.
INFO:USMMCM:Creating USMMCM, speedgrade -2.
INFO:USMMCM:Registering Differential ClkIn of 125.00MHz.
INFO:USMMCM:Creating ClkOut0 pll4x of 500.00MHz (+-10000.00ppm).
INFO:USMMCM:Creating ClkOut1 idelay of 500.00MHz (+-10000.00ppm).
INFO:USMMCM:Creating ClkOut2 uart of 125.00MHz (+-10000.00ppm).
INFO:SoCCSRHandler:leds CSR allocated at Location 5.
INFO:SoCCSRHandler:ddrphy CSR allocated at Location 6.
INFO:SoCCSRHandler:controller_settings CSR allocated at Location 7.
INFO:SoCCSRHandler:sdram CSR allocated at Location 8.
INFO:SoCBusHandler:main_ram Region added at Origin: 0x40000000, Size: 0x40000000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:main_ram added as Bus Slave.
INFO:SoCBusHandler:uartbone added as Bus Master.
INFO:SoCCSRHandler:rowhammer CSR allocated at Location 9.
INFO:SoCBusHandler:pattern_data Region added at Origin: 0x20000000, Size: 0x00000400, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:pattern_data added as Bus Slave.
INFO:SoC:RAM pattern_data added Origin: 0x20000000, Size: 0x00000400, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:pattern_addr Region added at Origin: 0x21000000, Size: 0x00000040, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:pattern_addr added as Bus Slave.
INFO:SoC:RAM pattern_addr added Origin: 0x21000000, Size: 0x00000040, Mode: RW, Cached: True Linker: False.
INFO:SoC:BIST pattern: Length: 16, Data Width: 512-bit, Address width: 32-bit
INFO:SoCCSRHandler:writer CSR allocated at Location 10.
INFO:SoCCSRHandler:reader CSR allocated at Location 11.
INFO:SoCBusHandler:payload Region added at Origin: 0x30000000, Size: 0x00000400, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:payload added as Bus Slave.
INFO:SoC:RAM payload added Origin: 0x30000000, Size: 0x00000400, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:scratchpad Region added at Origin: 0x31000000, Size: 0x00000400, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:scratchpad added as Bus Slave.
INFO:SoC:RAM scratchpad added Origin: 0x31000000, Size: 0x00000400, Mode: R, Cached: True Linker: False.
INFO:SoC:Instruction payload: Length: 256, Data Width: 32-bit
INFO:SoC:Scratchpad memory: Length: 16, Data Width: 512-bit
INFO:SoCCSRHandler:payload_executor CSR allocated at Location 12.
INFO:USMMCM:Config:
divclk_divide : 1
clkout2_freq  : 125.00MHz
clkout2_divide: 8
clkout2_phase : 0.00°
clkout0_freq  : 500.00MHz
clkout0_divide: 2
clkout0_phase : 0.00°
clkout1_freq  : 500.00MHz
clkout1_divide: 2
clkout1_phase : 0.00°
vco           : 1000.00MHz
clkfbout_mult : 8
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Finalized SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
IO Regions: (1)
io0                 : Origin: 0x00000000, Size: 0x100000000, Mode: RW, Cached: False Linker: False
Bus Regions: (5)
pattern_data        : Origin: 0x20000000, Size: 0x00000400, Mode: RW, Cached: True Linker: False
pattern_addr        : Origin: 0x21000000, Size: 0x00000040, Mode: RW, Cached: True Linker: False
payload             : Origin: 0x30000000, Size: 0x00000400, Mode: RW, Cached: True Linker: False
scratchpad          : Origin: 0x31000000, Size: 0x00000400, Mode: R, Cached: True Linker: False
main_ram            : Origin: 0x40000000, Size: 0x40000000, Mode: RW, Cached: True Linker: False
Bus Masters: (1)
- uartbone
Bus Slaves: (5)
- main_ram
- pattern_data
- pattern_addr
- payload
- scratchpad
INFO:SoC:32-bit CSR Bus, 32-bit Aligned, 16.0KiB Address Space, 2048B Paging, big Ordering (Up to 32 Locations).
CSR Locations: (13)
- ctrl                : 0
- identifier_mem      : 1
- uart_phy            : 2
- uart                : 3
- timer0              : 4
- leds                : 5
- ddrphy              : 6
- controller_settings : 7
- sdram               : 8
- rowhammer           : 9
- writer              : 10
- reader              : 11
- payload_executor    : 12
INFO:SoC:IRQ Handler (up to 32 Locations).
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCBusHandler:csr Region added at Origin: 0x00000000, Size: 0x00010000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:csr added as Bus Slave.
INFO:SoCCSRHandler:bridge added as CSR Master.
INFO:SoCBusHandler:Interconnect: InterconnectShared (1 <-> 6).

****** Vivado v2019.2 (64-bit)
  **** SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
  **** IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

WARNING: 'open_hw' is deprecated, please use 'open_hw_manager' instead.
open_hw_manager
INFO: [Labtools 27-2285] Connecting to hw_server url TCP:localhost:3121
INFO: [Labtools 27-2222] Launching hw_server...
INFO: [Labtools 27-2221] Launch Output:

****** Xilinx hw_server v2019.2
  **** Build date : Nov  6 2019 at 22:13:42
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

INFO: [Labtools 27-3415] Connecting to cs_server url TCP:localhost:3042
INFO: [Labtools 27-3417] Launching cs_server...
INFO: [Labtools 27-2221] Launch Output:

****** Xilinx cs_server v2019.2.0
  **** Build date : Nov 06 2019-21:41:48
    ** Copyright 2017-2019 Xilinx, Inc. All Rights Reserved.

INFO: [Labtoolstcl 44-466] Opening hw_target localhost:3121/xilinx_tcf/Xilinx/25683A
INFO: [Labtools 27-3164] End of startup status: HIGH
program_hw_devices: Time (s): cpu = 00:00:11 ; elapsed = 00:00:11 . Memory (MB): peak = 1469.859 ; gain = 0.000 ; free physical = 5844 ; free virtual = 23135
**INFO: [Labtools 27-1434] Device xczu7 (JTAG device index = 0) is programmed with a design that has no supported debug core(s) in it.**
INFO: [Common 17-206] Exiting Vivado at Fri Dec  4 19:09:39 2020...

**Comment by sqazi** [comment]
Also, the documentation mentions a correct USB port.  How do I know which one?  I see three ttyUSB*, and neither seem to work.

**Comment by jedrzejboczar** [comment]
Hi, as for uploading the bitstream, the warning is normal, and is not a problem. You can verify that the bitstream has been uploaded by checking the LEDs next to the 4 push buttons (near the FTDI chip connected to microUSB). They should start flashing in a circular pattern (`out[3:0] <= {out[2:0], ~out[3]}`).

Indeed the number of USB ports may be confusing. There is an FTDI chip on the board that actually has 4 channels, those are (from UG1267, ZCU104 Board User Guide):
```
* Channel A is configured to support the JTAG chain.
* Channel B implements UART0 MIO18/19 connections.
* Channel C implements UART1 MIO20/21 connections.
* Channel D implements UART2 PL-side bank 28 4-wire interface.
```
Currently we are using the UART connected to PL, so channel D. The channels should generally (but I am not entirely sure if this is guaranteed) show up as subsequent `/dev/ttyUSBx` devices, so if you have no other devices connected then channel D should be `/dev/ttyUSB3`. More specifically it should be the device on USB interface 3 of the FTDI (you could search in `ls /sys/bus/usb/devices/*.3/` with * being the device - there should be e.g. `ttyUSB3` directory inside.

Then you should run `litex_server --uart --uart-port /dev/ttyUSB3 --uart-baudrate 1e6`. To test that it's working, you can run `python rowhammer_tester/scripts/dump_regs.py`. I noticed that sometimes it hangs at first time, and only after I restart the litex_server and try again it works properly. This will not be an issue after we merege https://github.com/antmicro/litex-rowhammer-tester/pull/19, which should be ready today.

If you have any other issues, feel free to write them here. After finishing https://github.com/antmicro/litex-rowhammer-tester/pull/19 I'll update the README and include info about the USB ports.

**Comment by sqazi** [comment]
Thank you.  It worked on the second try:

$ python ./dump_regs.py 
Using generated target files in: ../../build/zcu104
0x00000000: 0x00000000 ctrl_reset
0x00000004: 0x12345678 ctrl_scratch
0x00000008: 0x00000000 ctrl_bus_errors
0x00001800: 0x00000000 uart_rxtx
0x00001804: 0x00000001 uart_txfull
0x00001808: 0x00000001 uart_rxempty
0x0000180c: 0x00000003 uart_ev_status
0x00001810: 0x00000000 uart_ev_pending
0x00001814: 0x00000000 uart_ev_enable
0x00001818: 0x00000001 uart_txempty
0x0000181c: 0x00000001 uart_rxfull
0x00002000: 0x00000000 timer0_load
0x00002004: 0x00000000 timer0_reload
0x00002008: 0x00000000 timer0_en
0x0000200c: 0x00000000 timer0_update_value
0x00002010: 0x00000000 timer0_value
0x00002014: 0x00000000 timer0_ev_status
0x00002018: 0x00000000 timer0_ev_pending
0x0000201c: 0x00000000 timer0_ev_enable
0x00002800: 0x00000000 leds_out
0x00003000: 0x00000000 ddrphy_rst
0x00003004: 0x00000001 ddrphy_en_vtc
0x00003008: 0x0000009e ddrphy_half_sys8x_taps
0x0000300c: 0x00000000 ddrphy_wlevel_en
0x00003010: 0x00000000 ddrphy_wlevel_strobe
0x00003014: 0x00000000 ddrphy_cdly_rst
0x00003018: 0x00000000 ddrphy_cdly_inc
0x0000301c: 0x00000000 ddrphy_cdly_value
0x00003020: 0x00000000 ddrphy_dly_sel
0x00003024: 0x00000000 ddrphy_rdly_dq_rst
0x00003028: 0x00000000 ddrphy_rdly_dq_inc
0x0000302c: 0x00000000 ddrphy_rdly_dq_bitslip_rst
0x00003030: 0x00000000 ddrphy_rdly_dq_bitslip
0x00003034: 0x00000000 ddrphy_wdly_dq_rst
0x00003038: 0x00000000 ddrphy_wdly_dq_inc
0x0000303c: 0x00000000 ddrphy_wdly_dqs_rst
0x00003040: 0x00000000 ddrphy_wdly_dqs_inc
0x00003044: 0x00000002 ddrphy_rdphase
0x00003048: 0x00000002 ddrphy_wrphase
0x00003800: 0x00000001 controller_settings_refresh
0x00004000: 0x00000001 sdram_dfii_control
0x00004004: 0x00000000 sdram_dfii_pi0_command
0x00004008: 0x00000000 sdram_dfii_pi0_command_issue
0x0000400c: 0x00000000 sdram_dfii_pi0_address
0x00004010: 0x00000000 sdram_dfii_pi0_baddress
0x00004014: 0x00000000 sdram_dfii_pi0_wrdata
0x00004024: 0x00000000 sdram_dfii_pi0_rddata
0x00004034: 0x00000000 sdram_dfii_pi1_command
0x00004038: 0x00000000 sdram_dfii_pi1_command_issue
0x0000403c: 0x00000000 sdram_dfii_pi1_address
0x00004040: 0x00000000 sdram_dfii_pi1_baddress
0x00004044: 0x00000000 sdram_dfii_pi1_wrdata
0x00004054: 0x00000000 sdram_dfii_pi1_rddata
0x00004064: 0x00000000 sdram_dfii_pi2_command
0x00004068: 0x00000000 sdram_dfii_pi2_command_issue
0x0000406c: 0x00000000 sdram_dfii_pi2_address
0x00004070: 0x00000000 sdram_dfii_pi2_baddress
0x00004074: 0x00000000 sdram_dfii_pi2_wrdata
0x00004084: 0x00000000 sdram_dfii_pi2_rddata
0x00004094: 0x00000000 sdram_dfii_pi3_command
0x00004098: 0x00000000 sdram_dfii_pi3_command_issue
0x0000409c: 0x00000000 sdram_dfii_pi3_address
0x000040a0: 0x00000000 sdram_dfii_pi3_baddress
0x000040a4: 0x00000000 sdram_dfii_pi3_wrdata
0x000040b4: 0x00000000 sdram_dfii_pi3_rddata
0x00004800: 0x00000000 rowhammer_enabled
0x00004804: 0x00000000 rowhammer_address1
0x00004808: 0x00000000 rowhammer_address2
0x0000480c: 0x00000000 rowhammer_count
0x00005000: 0x00000000 writer_start
0x00005004: 0x00000001 writer_ready
0x00005008: 0x00000000 writer_count
0x0000500c: 0x00000000 writer_done
0x00005010: 0x00000000 writer_mem_mask
0x00005014: 0x00000000 writer_data_mask
0x00005800: 0x00000000 reader_start
0x00005804: 0x00000001 reader_ready
0x00005808: 0x00000000 reader_count
0x0000580c: 0x00000000 reader_done
0x00005810: 0x00000000 reader_mem_mask
0x00005814: 0x00000000 reader_data_mask
0x00005818: 0x00000000 reader_error_count
0x0000581c: 0x00000000 reader_skip_fifo
0x00005820: 0x00000000 reader_error_offset
0x00005824: 0x00000000 reader_error_ready
0x00006000: 0x00000000 payload_executor_start
0x00006004: 0x00000001 payload_executor_status
0x00006008: 0x00000000 payload_executor_read_count

**Comment by sqazi** [comment]
Also, is mem.py supposed to work?  I am getting this?

$ python ./mem.py 
Using generated target files in: ../../build/zcu104
SDRAM initialization:
(ctl) Release reset
(ctl) Bring CKE high
(cmd) Load Mode Register 2, CWL=5
(cmd) Load Mode Register 3
(cmd) Load Mode Register 1
(cmd) Load Mode Register 0, CL=6, BL=8
(cmd) ZQ Calibration

Write leveling:
Cmd/Clk delay: 271
Module 0: delay 9
Module 1: delay 9
Module 2: delay 43
Module 3: delay 49
Module 4: delay 81
Module 5: delay 88
Module 6: delay 127
Module 7: delay 93

Read leveling:
Module 0: bitslip=2, delay=184
Module 1: bitslip=2, delay=184
Module 2: bitslip=2, delay=136
Module 3: bitslip=2, delay=136
Module 4: bitslip=3, delay=368
Module 5: bitslip=3, delay=360
Module 6: bitslip=3, delay=328
Module 7: bitslip=3, delay=296

Memtest (basic)
FAIL: errors = 8192

Memtest (random)
FAIL: errors = 8192

**Comment by jedrzejboczar** [comment]
Yes, mem.py should work. Could you try running it with the newest change https://github.com/antmicro/litex-rowhammer-tester/commit/75f7c93d446283a7d672ac073a1de3ec3c560473? It will perform full read leveling, which may take some time over UART, but should fix the problem. 

Also, just to be sure, you are using this module :https://github.com/antmicro/litex-rowhammer-tester/blob/master/rowhammer_tester/targets/zcu104.py#L70? (I remember that you said you have that one, but just want to double check).

**Comment by sqazi** [comment]
No luck with the specified commit ID.  I re-verified the part number.  It is the same.  The behaviour of mem.py with and without the memory seems to be identical.

$ python ./mem.py 
Using generated target files in: ../../build/zcu104
SDRAM initialization:
(ctl) Release reset
(ctl) Bring CKE high
(cmd) Load Mode Register 2, CWL=5
(cmd) Load Mode Register 3
(cmd) Load Mode Register 1
(cmd) Load Mode Register 0, CL=6, BL=8
(cmd) ZQ Calibration

Write leveling:
Cmd/Clk delay: 271
Module 0: delay 9
Module 1: delay 9
Module 2: delay 43
Module 3: delay 49
Module 4: delay 81
Module 5: delay 88
Module 6: delay 127
Module 7: delay 93

Read leveling:
Module 0
Bitslip 00: |00000000000000000000000000000000|
Bitslip 01: |00000000000000000000000000000000|
Bitslip 02: |00000000000000000000000000000000|
Bitslip 03: |00000000000000000000000000000000|
Bitslip 04: |00000000000000000000000000000000|
Bitslip 05: |00000000000000000000000000000000|
Bitslip 06: |00000000000000000000000000000000|
Bitslip 07: |00000000000000000000000000000000|
Read leveling failed
Module 1
Bitslip 00: |00000000000000000000000000000000|
Bitslip 01: |00000000000000000000000000000000|
Bitslip 02: |00000000000000000000000000000000|
Bitslip 03: |00000000000000000000000000000000|
Bitslip 04: |00000000000000000000000000000000|
Bitslip 05: |00000000000000000000000000000000|
Bitslip 06: |00000000000000000000000000000000|
Bitslip 07: |00000000000000000000000000000000|
Read leveling failed
Module 2
Bitslip 00: |00000000000000000000000000000000|
Bitslip 01: |00000000000000000000000000000000|
Bitslip 02: |00000000000000000000000000000000|
Bitslip 03: |00000000000000000000000000000000|
Bitslip 04: |00000000000000000000000000000000|
Bitslip 05: |00000000000000000000000000000000|
Bitslip 06: |00000000000000000000000000000000|
Bitslip 07: |00000000000000000000000000000000|
Read leveling failed
Module 3
Bitslip 00: |00000000000000000000000000000000|
Bitslip 01: |00000000000000000000000000000000|
Bitslip 02: |00000000000000000000000000000000|
Bitslip 03: |00000000000000000000000000000000|
Bitslip 04: |00000000000000000000000000000000|
Bitslip 05: |00000000000000000000000000000000|
Bitslip 06: |00000000000000000000000000000000|
Bitslip 07: |00000000000000000000000000000000|
Read leveling failed
Module 4
Bitslip 00: |00000000000000000000000000000000|
Bitslip 01: |00000000000000000000000000000000|
Bitslip 02: |00000000000000000000000000000000|
Bitslip 03: |00000000000000000000000000000000|
Bitslip 04: |00000000000000000000000000000000|
Bitslip 05: |00000000000000000000000000000000|
Bitslip 06: |00000000000000000000000000000000|
Bitslip 07: |00000000000000000000000000000000|
Read leveling failed
Module 5
Bitslip 00: |00000000000000000000000000000000|
Bitslip 01: |00000000000000000000000000000000|
Bitslip 02: |00000000000000000000000000000000|
Bitslip 03: |00000000000000000000000000000000|
Bitslip 04: |00000000000000000000000000000000|
Bitslip 05: |00000000000000000000000000000000|
Bitslip 06: |00000000000000000000000000000000|
Bitslip 07: |00000000000000000000000000000000|
Read leveling failed
Module 6
Bitslip 00: |00000000000000000000000000000000|
Bitslip 01: |00000000000000000000000000000000|
Bitslip 02: |00000000000000000000000000000000|
Bitslip 03: |00000000000000000000000000000000|
Bitslip 04: |00000000000000000000000000000000|
Bitslip 05: |00000000000000000000000000000000|
Bitslip 06: |00000000000000000000000000000000|
Bitslip 07: |00000000000000000000000000000000|
Read leveling failed
Module 7
Bitslip 00: |00000000000000000000000000000000|
Bitslip 01: |00000000000000000000000000000000|
Bitslip 02: |00000000000000000000000000000000|
Bitslip 03: |00000000000000000000000000000000|
Bitslip 04: |00000000000000000000000000000000|
Bitslip 05: |00000000000000000000000000000000|
Bitslip 06: |00000000000000000000000000000000|
Bitslip 07: |00000000000000000000000000000000|
Read leveling failed

Memtest (basic)
FAIL: errors = 8192

Memtest (random)
FAIL: errors = 8192

Also, I tried the top of the tree, but I got stuck, because I don't know where to obtain the zcu104.img file.

**Comment by jedrzejboczar** [comment]
I merged an update that adds a minimal CPU that will perform the DRAM initialization. It should solve the problem, as I suspect the issues you experience are due to improper write leveling. It will probably be a better solution, especially in terms of maintainability, as we will reuse even more of the infrastructure of LiteDRAM/LiteX.

You will need to re-run `make deps` and generate a new bitstream. The rest should be the same as before, `mem.py` script will wait for the CPU to finish. Currently you may see malformed stdout from the CPU, this is most likely due to the way our AXI->WishBone connection works and the way we retrieve UART output from CPU. CPU provides a CSR that we read to retrieve subsequent characters, but as we have a wide AXI bus, each read access actually reads multiple characters from CPU and some of them are dropped. Nevertheless initialization should work correctly, and you should be able to run the rest of the scripts the same as on Arty.

**Comment by jedrzejboczar** [comment]
One thing I forgot, you will also need gcc-riscv64 toolchain, on Ubuntu you could install the `gcc-riscv64-linux-gnu` package, I added a note about it in the README.

**Comment by sqazi** [comment]
mem.py works now.  Thank you for all your help.  I will close this, and complain about something else in a different bug :).
