### ISSUE TITLE
Large number of hammers appears to cause error reporting failure

### ISSUE THREAD

**Issue by sqazi** [antmicro/litex-rowhammer-tester#24]
Consider this command:

python hw_rowhammer.py  --nrows 512 --read_count 20e6 --pattern 01_in_row --row-pairs const --const-rows-pair 131 133  --no-refresh

If I run w/ 0.8e6 hammers, I get this:
.
.
.
Bit-flips for row   130: 19
Bit-flips for row   132: 748
Bit-flips for row   134: 25

which is fine.  If I increase to 20e6, I get this:
.
.
.
Progress: [========================================] 16777216 / 16777216 (Errors: 386) 
Traceback (most recent call last):
  File "hw_rowhammer.py", line 128, in <module>
    main(row_hammer_cls=HwRowHammer)
  File "/home/sqazi/fpga/litex-rowhammer-tester/rowhammer_tester/scripts/rowhammer.py", line 285, in main
    row_hammer.run(row_pairs=row_pairs, read_count=args.read_count, pattern_generator=pattern)
  File "hw_rowhammer.py", line 117, in run
    errors = self.check_errors(row_pattern)
  File "hw_rowhammer.py", line 77, in check_errors
    base_addr = min(self.addresses_per_row[row])
KeyError: 4240

**Comment by jedrzejboczar** [comment]
Thanks for reporting, should be fixed now.
