### ISSUE TITLE
Add instruction to terminate payload execution earlier

### ISSUE THREAD

**Issue by jedrzejboczar** [antmicro/litex-rowhammer-tester#32]
As disscussed in https://github.com/antmicro/litex-rowhammer-tester/pull/30#issuecomment-759639699 we would like an instruction that would terminate payload execution without having to execute whole payload memory.

It seems reasonable to use `NOOP` with `timeslice=0` for this purpose. This way memory filled with all zeros would instantly finish execution. Currently instructions with `timeslice=0` take 1 cycle to execute (in general `timeslice + 1` cycles). With the proposed change we would need to change interpretation of `timeslice` to be exactly the number of instruction execution cycles. 

This solution introduces a case for instructions other than `NOOP` with `timeslice=0`. It would be very counterintuitive to interpret `timeslice` differently for `NOOP` than for other instructions. But then we have a case where `timeslice=0` is illegal for instructions other than `NOOP` (because we need at least 1 cycle for execution).

I would propose to always have `cycles=timeslice`. Non-`NOOP` with `timeslice=0` would be an "illegal instruction". In the implementation it will most likely be silently executed the same as if `timeslice=1`, but this will be considered "undefined behavior". Would it be ok?

**Comment by sqazi** [comment]
It is okay to have undefined behaviour, as long as we can catch it in the python wrappers when someone attempts to use an illegal instruction.
