### ISSUE TITLE
Add make flash target

### ISSUE THREAD

**Issue by kgugala** [antmicro/litex-rowhammer-tester#63]
Both Arty and LPDDR4 test board targets support permanent configuration of the board (a bitstream can be load to on-board's QSPI flash and the FPGA will be autoconfigured on startup).

We should add a `flash` target to the main Makefile, so a user can update on-board's flash with simple `make flash` command

**Comment by tjurtsch** [comment]
"make flash" was added in https://github.com/antmicro/litex-rowhammer-tester/pull/65
