### ISSUE TITLE
Edit button on ReadTheDocs doesn't seem to work

### ISSUE THREAD

**Issue by mithro** [antmicro/litex-rowhammer-tester#77]
The Edit button found on most of the ReadTheDocs pages for this repository doesn't seem to work, it just takes you back to the same page;
![image](https://user-images.githubusercontent.com/21212/148251036-70c0f63b-c81d-4d4e-86c0-91a864903953.png)

**Comment by kgugala** [comment]
I've removed the Edit button and replaced it with:
![image](https://user-images.githubusercontent.com/3785621/148266981-a5a58cdd-55f9-4cc9-8684-101a0e33290d.png)

**Comment by mithro** [comment]
The Edit link was suppose to take you directly to the file in GitHub repository...

**Comment by pgielda** [comment]
Tbh the edit button was a leftover from our internal system...

**Comment by mithro** [comment]
"Edit" links are quite common on ReadTheDocs sites - https://docs.pylonsproject.org/projects/pyramid/en/master/ 

https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html
https://stackoverflow.com/a/66238784/3824056
